// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWuOknQIOsz6DUr3_zWChqGsPbQQKAXZE',
    appId: '1:655468386229:web:4cbcf47fe3c8dd2ed42bfc',
    messagingSenderId: '655468386229',
    projectId: 'pls-student',
    authDomain: 'pls-student.firebaseapp.com',
    storageBucket: 'pls-student.appspot.com',
    measurementId: 'G-3YXSZFQ281',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4UjdeebAt3SgFLzah97nJiBKsz4KMP5U',
    appId: '1:655468386229:android:6b190558a03cf5afd42bfc',
    messagingSenderId: '655468386229',
    projectId: 'pls-student',
    storageBucket: 'pls-student.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOqqOS5Ph_gYIrRVaP2bWKIf8qAN-_VI0',
    appId: '1:655468386229:ios:9f1257e14e3fae69d42bfc',
    messagingSenderId: '655468386229',
    projectId: 'pls-student',
    storageBucket: 'pls-student.appspot.com',
    iosBundleId: 'com.example.saeChang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOqqOS5Ph_gYIrRVaP2bWKIf8qAN-_VI0',
    appId: '1:655468386229:ios:9f1257e14e3fae69d42bfc',
    messagingSenderId: '655468386229',
    projectId: 'pls-student',
    storageBucket: 'pls-student.appspot.com',
    iosBundleId: 'com.example.saeChang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWuOknQIOsz6DUr3_zWChqGsPbQQKAXZE',
    appId: '1:655468386229:web:caa0069fdbb43aacd42bfc',
    messagingSenderId: '655468386229',
    projectId: 'pls-student',
    authDomain: 'pls-student.firebaseapp.com',
    storageBucket: 'pls-student.appspot.com',
    measurementId: 'G-8BRXG9WPNP',
  );
}
