enum AppText {
  txtHanNguSaeChang,
  txtLogin,
  txtLoginTitle,
  txtLetLogin,
  txtForgotPassword,
  txtContactSPForPassword,
  txtContactSp,
  txtStudySections,
  txtLevel1,
  txtLevel2,
  txtLevel3,
  txtLevel4,
  txtLevel5,
  txtHSK,
  txtForStudent,
  txtLoginSuccess,
  txtNotAccess,
  txtEmail,
  txtPassword,
  txtEmailNotEmpty,
  txtPasswordNotEmpty,
  txtPasswordInvalid,
  txtEmailInvalid,
  txtUserNotFound,
  txtLogout,
  txtSetting,
  txtVocabulary,
  txtListening,
  txtReading,
  txtGrammar,
  txtYourCourse,
  txtPromotion,
  txtRecommendCourse,
  txtGeneralKnowledge,
  txtOverview,
  txtLesson,
  txtTest,
  txtElective,
  txtPercentAttendance,
  txtPercentBTVN,
  txtScoreBTVN,
  txtScoreTest,
  txtListLessonEmptyWhenNotConnect,
  txtNotDoHomework,
  txtLessonNotStart,
  txtNotCheck,
  txtLate,
  txtOutSoon,
  txtLateAndOutSoon,
  txtJoin,
  txtPermission,
  txtUnauthorized,
  txtAttend,
  txtTestEmpty,
  txtScore,
  txtPrevious,
  txtNext,
  txtConfirmSubmit,
  txtTimeOver,
  txtSystemAutoSubmit,
  txtRemindSubmit,
  txtSubmit,
  txtReturn,
  txtPleaseGrantPermission,
  txtGrantPermission,
  txtIgnore,
  txtRecordError,
  txtInternetFailed,
  txtNoInternet,
  txtSubTitleDisconnect1,
  txtSubTitleDisconnect2,
  txtBack,
  txtContinue,
  txtEnd,
  txtSeeMore,
  txtTapToRecord,
  txtTapToEndRecord,
  txtOpenCamera,
  txtOpenGallery,
  txtReDraw,
  txtIgnoreQuestion,
  txtBestPractice,
  txtBadPractice,
  txtWaitForMark,
  txtYourAnswer,
  txtSeeResult,
  txtAnswer,
  txtExplain,
  txtTeacherNote,
  txtLessonEmpty,
  txtForce,
  txtFlashcard,
  txtHomework,
  txtLetPractice,
  txtNotDoPractice,
  txtNotDonePractice,
  txtDonePractice,
  txtListeningPractice,
  txtFloatLecture,
  txtNotify,
  txtUsage,
  txtStructure,
  txtSignal,
  txtConfirmLogout,
  btnPractice
}

Map<AppText, String> texts = {
  AppText.btnPractice: "Luyện tập",
  AppText.txtConfirmLogout: 'Bạn có chắc là muốn đăng xuất hay không?',
  AppText.txtFloatLecture: 'Video',
  AppText.txtNotify: 'Chú ý',
  AppText.txtUsage: 'Cách dùng',
  AppText.txtStructure: 'Cấu trúc',
  AppText.txtSignal: 'Dấu hiệu',
  AppText.txtListeningPractice: 'Luyện nghe',
  AppText.txtNotDoPractice: 'Chưa làm',
  AppText.txtNotDonePractice: 'Chưa hoàn thành',
  AppText.txtDonePractice: 'Đã hoàn thành',
  AppText.txtLetPractice:
  'Hãy luyện tập nhiều hơn để có thể nhớ bài nào bạn ơi!',
  AppText.txtHomework: 'Bài tập về nhà',
  AppText.txtFlashcard: 'FlashCard',
  AppText.txtForce: 'Phần bắt buộc',
  AppText.txtLessonEmpty: 'Buổi học này hiện \nkhông có bài tập về nhà',
  AppText.txtExplain: 'GIẢI THÍCH',
  AppText.txtTeacherNote: 'GHI CHÚ CỦA GIÁO VIÊN',
  AppText.txtAnswer: 'Đáp án đúng:  ',
  AppText.txtSeeResult: 'Xem kết quả',
  AppText.txtYourAnswer: 'Đáp án của bạn:  ',
  AppText.txtBestPractice: 'Bạn làm tốt lắm!\nHãy tiếp tục phát huy nhé',
  AppText.txtBadPractice: 'Điểm số chưa ổn lắm!\nCố gắng hơn nữa nhé',
  AppText.txtWaitForMark: 'Kết quả đang được chấm.\nBạn đợi một tí nhé!',
  AppText.txtIgnoreQuestion: 'Bạn đã bỏ qua câu này!',
  AppText.txtReDraw: 'Vẽ lại',
  AppText.txtOpenCamera: 'Chụp ảnh',
  AppText.txtOpenGallery: 'Chọn từ thư viện',
  AppText.txtTapToRecord: 'Nhấn để bắt đầu ghi âm',
  AppText.txtTapToEndRecord: 'Nhấn thêm một lần nữa để kết thúc ghi âm',
  AppText.txtSeeMore: 'Xem thêm...',
  AppText.txtEnd: 'Kết thúc',
  AppText.txtContinue: 'Tiếp tục',
  AppText.txtBack: 'Quay lại',
  AppText.txtNoInternet: 'Không có kết nối mạng',
  AppText.txtSubTitleDisconnect1: 'Bạn ơi kiểm tra lại đường truyền rồi thử lại nha. Hoặc bạn có thể sử dụng tính năng mà không cần kết nối mạng.',
  AppText.txtSubTitleDisconnect2: 'Bạn ơi kiểm tra lại đường truyền rồi thử lại nha. Bạn cần kết nối mạng để sử dụng tính năng này.',
  AppText.txtInternetFailed: 'Mất kết nối mạng! Vui lòng thử lại.',
  AppText.txtRecordError: 'Quá trình ghi âm bị lỗi! Hãy thử lại.',
  AppText.txtIgnore: 'Bỏ qua',
  AppText.txtGrantPermission: 'Cấp quyền',
  AppText.txtPleaseGrantPermission:
  'Vui lòng cấp quyền micro để sử dụng tính năng!',
  AppText.txtReturn: 'Quay lại',
  AppText.txtSubmit: 'Nộp bài',
  AppText.txtNext: 'Tiếp theo',
  AppText.txtConfirmSubmit: 'Bạn có chắc là muốn nộp bài hay không?',
  AppText.txtTimeOver: 'Hết giờ làm bài!',
  AppText.txtSystemAutoSubmit:
  'Hệ thống đang tự động nộp bài! Vui lòng chờ trong giây lát...',
  AppText.txtRemindSubmit:
  'Bạn sẽ không thể thay đổi đáp án hay làm lại bài sau khi nộp.',
  AppText.txtPrevious: 'Quay về',
  AppText.txtScore: 'Điểm',
  AppText.txtTestEmpty: 'Lớp hiện chưa có bài kiểm tra nào.',
  AppText.txtJoin: 'Đã tham gia',
  AppText.txtPermission: 'Nghỉ có phép',
  AppText.txtUnauthorized: 'Nghỉ không phép',
  AppText.txtAttend: 'Đi học',
  AppText.txtNotCheck: 'Chưa điểm danh',
  AppText.txtLate: 'Vô trễ',
  AppText.txtOutSoon: 'Ra sớm',
  AppText.txtLateAndOutSoon: 'Vô trễ & ra sớm',
  AppText.txtLessonNotStart: 'Chưa bắt đầu',
  AppText.txtNotDoHomework: 'Nợ Bài Tập Về Nhà',
  AppText.txtListLessonEmptyWhenNotConnect:
  'Bạn chưa load bất cứ bài học nào để có thể học ở chế độ offline!',
  AppText.txtPercentAttendance: "Tỉ lệ đi học",
  AppText.txtPercentBTVN: "Tỉ lệ làm btvn",
  AppText.txtScoreBTVN: "Điểm btvn",
  AppText.txtScoreTest: "Điểm kiểm tra",
  AppText.txtOverview: "Tổng quan",
  AppText.txtLesson: "Bài học",
  AppText.txtTest: "Kiểm tra",
  AppText.txtElective: "Tự học",
  AppText.txtVocabulary: "Từ vựng",
  AppText.txtListening: "Nghe",
  AppText.txtReading: "Đọc",
  AppText.txtGrammar: "Ngữ pháp",
  AppText.txtHanNguSaeChang: "Hàn Ngữ Sae-Chang",
  AppText.txtYourCourse: "Khoá học của bạn",
  AppText.txtPromotion: "Khuyến mãi",
  AppText.txtRecommendCourse: "Khoá học đề xuất",
  AppText.txtGeneralKnowledge: "Kiến thức tổng quát",
  AppText.txtLogin: "Đăng nhập",
  AppText.txtLoginTitle: "Dành riêng cho học viên Sae-Chang",
  AppText.txtLetLogin:
      "Sẵn sàng khám phá kiến thức cùng Sae Chang với kho bài học phong phú nhé!",
  AppText.txtForgotPassword: "Quên mật khẩu?",
  AppText.txtContactSPForPassword:
      "Bạn hãy nhấn nút dưới để có thể liên lạc với Team Support để được cung cấp mật khẩu mới nhé!",
  AppText.txtContactSp: "Liên hệ Team Support",
  AppText.txtStudySections: "Học phần",
  AppText.txtLevel1: "Bắt đầu",
  AppText.txtLevel2: "Sơ cấp",
  AppText.txtLevel3: "Trung cấp",
  AppText.txtLevel4: "Cao cấp 1",
  AppText.txtLevel5: "Cao cấp 2",
  AppText.txtHSK: "HSK @",
  AppText.txtForStudent: "Dành cho học viên",
  AppText.txtLoginSuccess: "Đăng nhập thành công",
  AppText.txtNotAccess: 'Bạn không có quyền truy cập app',
  AppText.txtEmail: "Email",
  AppText.txtPassword: "Mật khẩu",
  AppText.txtEmailNotEmpty: 'Vui lòng nhập email',
  AppText.txtPasswordNotEmpty: 'Vui lòng nhập password',
  AppText.txtPasswordInvalid: 'Sai mật khẩu',
  AppText.txtEmailInvalid: 'Email không hợp lệ',
  AppText.txtUserNotFound: 'Tài khoản không tồn tại',
  AppText.txtLogout: "Đăng xuất",
  AppText.txtSetting: "Cài đặt",
};
extension AppTexts on AppText {
  static String getStringValue(String value) {
    return value;
  }

  String get text => texts[this] ?? '--TextNotFound--';
}